# Generated by Django 3.0.5 on 2020-08-06 20:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Bed Rooms'), (2, 'Bath Rooms'), (3, 'Luggage'), (4, 'Garage'), (5, 'Water'), (6, 'Stories'), (7, 'Roofing')], max_length=13),
        ),
    ]
