# Generated by Django 3.0.5 on 2020-08-06 20:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200806_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Bed Rooms'), (2, 'Bath Rooms'), (3, 'Luggage'), (4, 'Garage'), (5, 'Water'), (6, 'Stories'), (7, 'Roofing')], max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='HouseModel',
        ),
    ]
