# Generated by Django 3.0.5 on 2020-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200806_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='url',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
