# Generated by Django 3.0.5 on 2020-08-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200806_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Image_Header',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
