# Generated by Django 3.0.5 on 2020-08-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_house_image_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Image_Header',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
