# Generated by Django 3.0.5 on 2020-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200806_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='Image_Header',
        ),
        migrations.AddField(
            model_name='house',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
