# Generated by Django 3.0.5 on 2020-08-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200806_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Price',
            field=models.FloatField(default=1.0),
        ),
    ]
