# Generated by Django 3.0.5 on 2020-08-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_house_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Price_per_month',
            field=models.FloatField(default=1.0),
        ),
    ]
