# Generated by Django 3.0.5 on 2020-08-07 15:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_house_price_per_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('Image', models.ImageField(default='default.jpg', upload_to='posts/')),
                ('tag1', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Jobs')], max_length=1)),
                ('tag2', multiselectfield.db.fields.MultiSelectField(choices=[(3, 'Coffe')], max_length=1)),
                ('tag3', multiselectfield.db.fields.MultiSelectField(choices=[(3, 'Travel')], max_length=1)),
            ],
        ),
    ]
