# Generated by Django 3.0.5 on 2020-08-07 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
