# Generated by Django 3.0.5 on 2020-08-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='house',
            field=models.CharField(default='', max_length=200),
        ),
    ]
